"""created users table

Revision ID: 3616a54903aa
Revises: 6fffb8f57189
Create Date: 2024-07-19 16:29:07.204613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3616a54903aa'
down_revision: Union[str, None] = '6fffb8f57189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
    pass
